### ISSUE TITLE
Emails rejected -  reject reason: Unsigned

### ISSUE THREAD

**Issue by przbadu** [renz45/mandrill_mailer#103]
I am using `mandrill_mailer (1.1.0)`:
```
mandrill_mailer (1.1.0)
      mandrill-api (~> 1.0.9)
```

All of my emails are rejecting with status

```
Reject reason: Unsigned
```

![outbound activity mandrill](https://cloud.githubusercontent.com/assets/4189129/11709304/87a74cf6-9f3e-11e5-9d98-3ff3def7aa92.png)

Not sure, how to fix this issue and what is the exact cause.

**Comment by renz45** [comment]
Sorry about not getting back to you, I must have completely missed the email notification. I'll take a quick look and see if anything jumps at me.

**Comment by renz45** [comment]
Is your account recently new with Mandrill? It looks like they just added another layer of domain verification for sending emails just this month. https://mandrill.zendesk.com/hc/en-us/articles/205582247

**Comment by renz45** [comment]
Ohh this one is better, mentions the error you've been getting:
https://mandrill.zendesk.com/hc/en-us/articles/205582267

**Comment by przbadu** [comment]
Hi,

I fixed it, the problem was with spelling mistake in email domain I
configured in mandrill

Thanks

**Comment by renz45** [comment]
Glad you figured it out :) :tada:

**Comment by stephen042** [comment]
i have authenticated my domain but it still shows unsigned error at the API log

**Comment by Scorpion1898** [comment]
Me too showing the same error message

**Comment by MohsinKhattak** [comment]
> i have authenticated my domain but it still shows unsigned error at the API log

have you found solution to it?
